### PR TITLE
fix: fix build on nix 2.17

### LINKED ISSUE #93: Not building with latest `nix`
After this commit https://github.com/nixos/nix/commit/22b278e011ab9c1328749a126514c57b89a39173 nil won't build. It can't find the `__dump-builtins` command, as it's been changed to `__dump-language`.

I think that it should first try `__dump-language`, and if that doesn't run, it should try `__dump-builtins` for people that might still be on an older version of `nix`.

### PR DESCRIPTION
**Pull request by n3oney**
Closes #93 

Should be fully backwards compatible.

Tested both on nix master 2.17 prerelease and nix 2.16 - builds fine on both!

### CODE REVIEW

File: crates/builtin/build.rs [hunk 1]
```diff
@@ -98,6 +110,11 @@ impl CommandExt for Command {
     }
 }
 
+#[derive(Debug, Deserialize)]
+struct DumpLanguage {
+    builtins: DumpBuiltins,
```
Comment (oxalica) [inline crates/builtin/build.rs:115]: The new CLI splits all builtins into `builtins` for functions and `constants` for values, and they have different structures. We should parse both of them with their kind information to replace the hard-coded names [here](https://github.com/oxalica/nil/blob/f6bd5fea84bb5b0b3685b5dd9c21c83fe6ab9b64/crates/builtin/build.rs#L66-L69).

I think we can move the `Command` call to `dump*` and the parsing code into a individual function. So the huge `map_or_else` above can also be refactored into an early return.

**Review by oxalica — CHANGES_REQUESTED** [review]

File: crates/builtin/build.rs [hunk 2]
```diff
@@ -52,12 +52,24 @@ fn main() {
             .collect()
     };
 
-    // Use a secret subcommand `__dump-builtins` to dump Nix builtins with documentations.
-    // It is introduced since Nix 2.4 in
-    // https://github.com/NixOS/nix/commit/0f314f3c2594e80322c675b70a61dcfda11bf423#diff-20a8b5b2a231db80eab27840bd32ac0214aa0c4e9e923e649d3d741c3da77b48R187
+    // Use a secret subcommand `__dump-language` to dump Nix builtins with documentations.
+    // It is introduced since Nix 2.7 in
```
[the remark this answers is not in the document]
Comment (n3oney) [reply crates/builtin/build.rs:56]: Yes, my bad, I mean 2.17

File: crates/builtin/build.rs (hunk 1 above)
Comment (n3oney) [reply crates/builtin/build.rs:115]: I'm honestly not sure what you mean.
I've compared the old `__dump-builtins` to `__dump-language`'s `builtins` property, and there's two differences - the new CLI has 4 more builtins - `findFile`, `fromTOML`, `getContext`, `hasContext`, and every value has an `experimental-feature` key under it.

Comment (oxalica) [reply crates/builtin/build.rs:115]: Constants like `true` and `storeDir` are documented under the new `constants` property, not `builtins` property, while they are not documented before. They should also be included.

Comment (n3oney) [reply crates/builtin/build.rs:115]: Oh, I see. I'm not that proficient in Rust, so I might need some help with that...

**Comment by oxalica** [comment]
I merged this now since it should have no regression. I'll handle the new `constants` map maybe later this week.
